version: '3'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=website_parsing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maksim2001
    ports:
      - '5445:5432'
  
  web:
    build: ./app
    command: ["./entrypoint.sh"]
    volumes:
      - statics_volume:/site/static
      - ./site/:/usr/src/site_main/
    environment:
      - POSTGRES_DB=website_parsing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maksim2001
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
    expose:
      - 8000
  
  parser:
    build:
      context: ./app
      dockerfile: Dockerfile.parser
    command: ["python", "parser_app/main.py"]
    environment:
      - POSTGRES_DB=website_parsing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maksim2001
      - POSTGRES_HOST=db
    volumes:
      - ./site/:/usr/src/site_main/
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1137:80
    volumes:
      - statics_volume:/usr/share/nginx/html/static
    depends_on:
      - web


volumes:
  pgdata:
  statics_volume: