# Generated by Django 4.1.7 on 2023-10-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="sitemap_url",
            field=models.URLField(
                blank=True, default=None, null=True, verbose_name="SITEMAP URL"
            ),
        ),
    ]
