# Generated by Django 4.1.7 on 2023-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_country_website_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=1000, verbose_name="Название статьи"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_translate",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Перевод названия"
            ),
        ),
    ]
