# Generated by Django 4.1.7 on 2023-10-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_article_title_alter_article_title_translate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(
                max_length=1000, unique=True, verbose_name="Ссылка на статью"
            ),
        ),
    ]
