# Generated by Django 4.1.7 on 2023-10-25 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_ignoredurl_users_website_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_countries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
