# Generated by Django 4.1.7 on 2023-10-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(max_length=100, verbose_name="Текст слова"),
        ),
    ]
