# Generated by Django 4.2.7 on 2023-11-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_tab_tabwebsite_tabtrackedword_tabcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tabcountry',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='tabtrackedword',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='tabtrackedword',
            name='tracked_word',
        ),
        migrations.RemoveField(
            model_name='tabwebsite',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='tabwebsite',
            name='website',
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
        migrations.DeleteModel(
            name='TabCountry',
        ),
        migrations.DeleteModel(
            name='TabTrackedWord',
        ),
        migrations.DeleteModel(
            name='TabWebsite',
        ),
    ]
