# Generated by Django 4.2.7 on 2023-11-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_remove_tabcountry_country_remove_tabcountry_tab_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PARENTS", "Родители"),
                    ("WELLNESS", "Здоровье"),
                    ("PARENTING", "Воспитание"),
                    ("COMEDY", "Комедия"),
                    ("POLITICS", "Политика"),
                    ("BLACK VOICES", "Черные Голоса"),
                    ("QUEER VOICES", "Квир-Голоса"),
                    ("ENTERTAINMENT", "Развлечения"),
                    ("CULTURE & ARTS", "Культура и Искусство"),
                    ("TECH", "Технологии"),
                    ("RELIGION", "Религия"),
                    ("STYLE & BEAUTY", "Стиль и Красота"),
                    ("HEALTHY LIVING", "Здоровый Образ Жизни"),
                    ("TRAVEL", "Путешествия"),
                    ("GREEN", "Экология"),
                    ("IMPACT", "Влияние"),
                    ("BUSINESS", "Бизнес"),
                    ("DIVORCE", "Развод"),
                    ("SCIENCE", "Наука"),
                    ("SPORTS", "Спорт"),
                    ("LATINO VOICES", "Латиноамериканские Голоса"),
                    ("WORLD NEWS", "Мировые Новости"),
                    ("HOME & LIVING", "Дом и Жизнь"),
                    ("MEDIA", "Медиа"),
                    ("U.S. NEWS", "Новости США"),
                    ("TASTE", "Вкус"),
                    ("FOOD & DRINK", "Еда и Напитки"),
                    ("WEIRD NEWS", "Странные Новости"),
                    ("STYLE", "Стиль"),
                    ("WOMEN", "Женщины"),
                    ("ARTS & CULTURE", "Искусство и Культура"),
                    ("CRIME", "Преступность"),
                    ("MONEY", "Деньги"),
                    ("WEDDINGS", "Свадьбы"),
                    ("ARTS", "Искусства"),
                    ("WORLDPOST", "Мировой Пост"),
                    ("THE WORLDPOST", "Мировой Пост (THE)"),
                    ("EDUCATION", "Образование"),
                    ("COLLEGE", "Колледж"),
                    ("GOOD NEWS", "Хорошие Новости"),
                    ("FIFTY", "Пятьдесят"),
                    ("ENVIRONMENT", "Окружающая Среда"),
                ],
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="eng_title",
            field=models.TextField(
                blank=True, null=True, verbose_name="Название статьи на английском"
            ),
        ),
    ]
