# Generated by Django 4.2.7 on 2023-11-25 10:08

from django.db import migrations, models
from django.db.models import F

def forward_func(apps, schema_editor):
    Article = apps.get_model("main", "Article")
    db_alias = schema_editor.connection.alias
    Article.objects.using(db_alias).all().update(created_at=F('published_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_article_category_article_eng_title'),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(verbose_name="Время добавления в БД", auto_now_add=True, db_index=True)
        ),
        
        migrations.RunPython(forward_func),
    ]
