# Generated by Django 4.2.7 on 2023-11-10 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_remove_tabcountry_country_remove_tabcountry_tab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вкладки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вкладка',
                'verbose_name_plural': 'Вкладки',
            },
        ),
        migrations.CreateModel(
            name='TabWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_websites', to='users.tab')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_tabs', to='main.website')),
            ],
            options={
                'verbose_name': 'Сайт во вкладке',
                'verbose_name_plural': 'Сайты во вкладке',
            },
        ),
        migrations.CreateModel(
            name='TabTrackedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_tracked_words', to='users.tab')),
                ('tracked_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_word_tabs', to='main.trackedword')),
            ],
            options={
                'verbose_name': 'Отслеживаемое слово во вкладке',
                'verbose_name_plural': 'Отслеживаемые слова во вкладке',
            },
        ),
        migrations.CreateModel(
            name='TabCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_tabs', to='main.country')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_countries', to='users.tab')),
            ],
            options={
                'verbose_name': 'Страна во вкладке',
                'verbose_name_plural': 'Страны во вкладке',
            },
        ),
    ]
