# Generated by Django 4.2.7 on 2023-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="session_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_info",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
