# Generated by Django 4.2.7 on 2023-11-24 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userdevice_session_key_alter_userdevice_device_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tab",
            options={
                "verbose_name": "Набор фильтров",
                "verbose_name_plural": "Наборы фильтров",
            },
        ),
        migrations.AlterModelOptions(
            name="tabcountry",
            options={
                "verbose_name": "Страна в наборе фильтров",
                "verbose_name_plural": "Страны в наборе фильтров",
            },
        ),
        migrations.AlterModelOptions(
            name="tabtrackedword",
            options={
                "verbose_name": "Отслеживаемое слово в наборе фильтров",
                "verbose_name_plural": "Отслеживаемые слова в наборе фильтров",
            },
        ),
        migrations.AlterModelOptions(
            name="tabwebsite",
            options={
                "verbose_name": "Сайт в наборе фильтров",
                "verbose_name_plural": "Сайты в наборе фильтров",
            },
        ),
        migrations.AlterField(
            model_name="tab",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название набора фильтров"
            ),
        ),
        migrations.CreateModel(
            name="TabCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PARENTS", "Родители"),
                            ("WELLNESS", "Здоровье"),
                            ("PARENTING", "Воспитание"),
                            ("COMEDY", "Комедия"),
                            ("POLITICS", "Политика"),
                            ("BLACK VOICES", "Черные Голоса"),
                            ("QUEER VOICES", "Квир-Голоса"),
                            ("ENTERTAINMENT", "Развлечения"),
                            ("CULTURE & ARTS", "Культура и Искусство"),
                            ("TECH", "Технологии"),
                            ("RELIGION", "Религия"),
                            ("STYLE & BEAUTY", "Стиль и Красота"),
                            ("HEALTHY LIVING", "Здоровый Образ Жизни"),
                            ("TRAVEL", "Путешествия"),
                            ("GREEN", "Экология"),
                            ("IMPACT", "Влияние"),
                            ("BUSINESS", "Бизнес"),
                            ("DIVORCE", "Развод"),
                            ("SCIENCE", "Наука"),
                            ("SPORTS", "Спорт"),
                            ("LATINO VOICES", "Латиноамериканские Голоса"),
                            ("WORLD NEWS", "Мировые Новости"),
                            ("HOME & LIVING", "Дом и Жизнь"),
                            ("MEDIA", "Медиа"),
                            ("U.S. NEWS", "Новости США"),
                            ("TASTE", "Вкус"),
                            ("FOOD & DRINK", "Еда и Напитки"),
                            ("WEIRD NEWS", "Странные Новости"),
                            ("STYLE", "Стиль"),
                            ("WOMEN", "Женщины"),
                            ("ARTS & CULTURE", "Искусство и Культура"),
                            ("CRIME", "Преступность"),
                            ("MONEY", "Деньги"),
                            ("WEDDINGS", "Свадьбы"),
                            ("ARTS", "Искусства"),
                            ("WORLDPOST", "Мировой Пост"),
                            ("THE WORLDPOST", "Мировой Пост (THE)"),
                            ("EDUCATION", "Образование"),
                            ("COLLEGE", "Колледж"),
                            ("GOOD NEWS", "Хорошие Новости"),
                            ("FIFTY", "Пятьдесят"),
                            ("ENVIRONMENT", "Окружающая Среда"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tab_categories",
                        to="users.tab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория в наборе фильтров",
                "verbose_name_plural": "Категории в наборе фильтров",
            },
        ),
    ]
