# Generated by Django 4.1.7 on 2023-10-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_article_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(verbose_name="Base URL to Ignore")),
            ],
        ),
    ]
