# Generated by Django 4.1.7 on 2023-10-24 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0007_ignoredurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="ignoredurl",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="ignored_urls", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_websites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
