# Generated by Django 4.1.7 on 2023-10-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Configuration Name"
                    ),
                ),
                (
                    "black_list_tags",
                    models.TextField(
                        default="NPRO,INTJ,CONJ,PREP,PRED,ADJF,NPRO,ADVB,ADJS,PRCL,INFN,VERB",
                        verbose_name="Черный список тегов(форм слов) для morph (comma-separated)",
                    ),
                ),
                (
                    "black_list_words",
                    models.TextField(
                        default="ТАСС",
                        verbose_name="Черный список слов для morph (comma-separated)",
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Время для анализа статей(ч)"
                    ),
                ),
                (
                    "top_words_count",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Счетчик Top Words"
                    ),
                ),
            ],
        ),
    ]
