# Generated by Django 4.1.7 on 2023-10-31 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_word_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Время создания",
            ),
            preserve_default=False,
        ),
    ]
